Faq.Interview/Models/InterviewViewModels.cs
using System;
using System.Collections.Generic;

public class DataListItem
{
    public string Value { get; set; }
    public string Text { get; set; }
}

public class AutocompleteListItem
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class ValidationViewModel
{

    public string Name { get; set; }
    public DateTime Date { get; set; }
    public bool Agreed { get; set; }
}

public class DinnerViewModel
{
    public DinnerViewModel()
    {
        Sizes = new List<Size>();
    }
    public string Name { get; set; }
    public string Description { get; set; }
    public List<Size> Sizes { get; set; }
}

public class Size
{
    public string Name { get; set; }
    public double Price { get; set; }
    public double Unit { get; set; }
}

public class Employee
{
    public Employee()
    {
        Salaries = new List<Salary>();
    }
    public int Id { get; set; }
    public string Name { get; set; }

    public List<Salary> Salaries { get; set; }
}

public class Salary
{
    public int EmployeeId { get; set; }
    public DateTime Date { get; set; }
    public double Amount { get; set; }
}

Faq.Interview/Controllers/InterviewController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using FAQ.Interview.Helper;

namespace Faq.Interview.Controllers
{
    public class InterviewController : Controller
    {
        public ActionResult Index(bool showInstructions = false)
        {
            if (showInstructions)
                TempData["SHOW_INSTRUCTIONS"] = "TRUE";
            else
                TempData["SHOW_INSTRUCTIONS"] = "";

            return View();
        }

        public ActionResult SaveData()
        {
            var model = new DinnerViewModel
            {
                Name = "This is a Name",
                Description = "<p>This is a description</p>",
                Sizes = new List<Size>
                {
                    new Size
                    {
                        Name = "Individual",
                        Price = 1.5,
                        Unit = .3
                    },
                    new Size
                    {
                        Name = "Small",
                        Price = 2,
                        Unit = 1
                    },
                    new Size
                    {
                        Name = "Large",
                        Price = 3.5,
                        Unit = 1.5
                    }
                }
            };

            return View(model);
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult SaveData(DinnerViewModel model)
        {
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Sql()
        {
            return View();
        }

        public ActionResult Report(int? month = null)
        {
            //Use this year value
            var year = DateTime.Today.Year;

            var dataProvider = new DataProvider();
            var data = dataProvider.Report(month);

            return View(data);
        }

        public ActionResult Problem()
        {
            return View();
        }
    }
}

Faq.Interview/Views/Interview/Index.cshtml
@{
    ViewBag.Title = "Index";
    var showInstructions = TempData["SHOW_INSTRUCTIONS"] != null && TempData["SHOW_INSTRUCTIONS"].ToString() == "TRUE";
    TempData["NAV"] = "INDEX";
}

@if (!showInstructions)
{
    <h2>Welcome to the practical interview.</h2>
    <br />
    <div>
        This test is about 4 common problems we work on daily basis.
        <br />
        Please click on the Read Instructions before you start. <br /> <br /> <a class="btn btn-success" href="/Interview/Index?showInstructions=true">Read Instructions</a>
    </div>
    return;
}

<h2>Welcome to the practical interview.</h2>
<br />
<p>There are <strong>4</strong> problems to solve in this project. Each menu represents a problem.</p>

<h3>Instructions</h3>
<p>Please Download the source code from the button below. After completion upload it to your github/bitbucket account and share with us in the following email address <strong>tokyo@faqi.com.au/</strong>.</p>
<pre>
<strong class="mgb"> Git commit example </strong>
      {Task Name} : {Time}
      
      Like 
      Data Post Issue : 1 hour
      Sql : .5 hour
      Report : 1.5 hour
</pre>

<p><strong>Good Luck!</strong></p>



<div>
    <a class="btn btn-success pull-left" href="/FaqInterview.zip">CLICK TO DOWNLOAD PROJECT SOURCE CODE HERE</a>
    <a class="btn btn-success pull-right" href="/interview/savedata">Next >></a>
</div>

Faq.Interview/Views/Interview/Problem.cshtml
@{
    ViewBag.Title = "Logical Problem";
    TempData["NAV"] = "PROBLEM";
}

<h2>Logical Problem</h2>
<div class="issue-description">
    Let's consider any game where players will score. The player with a high score will be ranked number 1. The player who has the same score will receive a same ranking number, and the next player(s) receive the immediately following ranking number.
    <br />
    <br />
    <strong> Example </strong>

    <p> ranked = [50,40,40,30] </p>
    <p> player = [25,30,100] </p>

    The ranked players will have ranks 1, 2, 2, and 3, respectively. if player scores are 25,30 and 100 their rankings after each game are 4th, 3rd, and 1st Return [4,3,1].

    <strong> Input parameter </strong>

    <ul>
        <li>int ranked[n]: the leaderboard scores</li>
        <li>int player[m]: the player's scores</li>
    </ul>

    <strong>Output</strong>
    <ul>
        <li>Return player rank array</li>
    </ul>

    <strong>Sample input</strong>
    <pre>
        7                                                            - array item count 
        100 100 50 40 40 20 10                                       - ranked[n]
        4                                                            - array item count
        5 25 50 120                                                  - player[n]
    </pre>

    <strong>Sample output</strong>
    <pre>
        6
        4
        2
        1
    </pre>

    <strong>Instructions</strong>
    <p>**You were given a console application inside the Console folder to work with.</p>
    <p>**input.txt file is in the root directory of the console application. Source code has file read functionality and arrays are already populated from the file.</p>
    <p>**Program.cs has a function where it receives 2 input arrays and returns the result. You will have to write your logic inside that function only and populate that array. The result will print.</p>
    <br />
    <br />
    <div class="clearfix">
        <a class="btn btn-success pull-left" href="/interview/report">&lt;&lt; Previous</a>
    </div>
 </div>

Faq.Interview/Views/Interview/Report.cshtml
@using System.Globalization
@model List<Employee>
@{
    ViewBag.Title = "Weekly salary seport";
    var months = Enumerable.Range(0, 12).Select(m => new DataListItem
    {
        Text = DateTimeFormatInfo.CurrentInfo.MonthNames[m],
        Value = (m + 1).ToString()
    });

    TempData["NAV"] = "REPORT";
    var amount = 0.0;
    DateTime date = DateTime.Today;
    var dates = Enumerable.Range(1, DateTime.DaysInMonth(date.Year, date.Month)).Select(n => new DateTime(date.Year, date.Month, n));
    var prevweekday = 0;
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $(document).ready(function () {
        $("#month").change(function () {
            window.location.href = "/Interview/Report?month=" + $("#month").val();
        })
    })
</script>

<h2>Weekly salary report </h2>

<div class="row">
    <div class="col-sm-6">
        <label class="challenge-title">Select Month</label>
        @Html.DropDownList("month",
            new SelectList(months, "Value", "Text"),
            "Please select a month",
            new { id = "month", @class = "auto-postback month-dropdown" })

        <br /> <br />

        <h4>Salary report</h4>
        <div class="row mgt mgb">
            <div class="col-sm-2"><strong>Name</strong></div>
            <div class="col-sm-2"><strong>Week 1</strong> </div>
            <div class="col-sm-2"><strong>Week 2</strong></div>
            <div class="col-sm-2"><strong>Week 3</strong></div>
            <div class="col-sm-2"><strong>Week 4</strong> </div>
            <div class="col-sm-2"><strong>Week 5</strong></div>
        </div>
        @{
            foreach (var item in Model)
            {
                <div class="row mgb-sm table-row">
                    @{
                        <div class="col-sm-2">@item.Name</div>
                        var salas = item.Salaries.Where(x => x.EmployeeId == item.Id).ToList();
                        dates = dates.Where(x => x.Date.DayOfWeek == DayOfWeek.Sunday).ToList();
                        foreach (var d in dates)
                        {
                            amount = 0.0;
                            if (prevweekday == 0)
                            {
                                var objsalas = salas.Where(x => x.Date.Day <= d.Date.Day).ToList();
                                if (objsalas != null && objsalas.Count > 0)
                                {
                                    foreach (var item1 in objsalas)
                                    {
                                        amount = amount + item1.Amount;
                                    }
                                }
                            }
                            else
                            {
                                var objsalas = salas.Where(x => x.Date.Day > prevweekday).ToList();
                                var objsalas1 = objsalas.Where(x => x.Date.Day <= d.Date.Day).ToList();
                                if (objsalas1 != null && objsalas1.Count > 0)
                                {
                                    foreach (var item1 in objsalas1)
                                    {
                                        amount = amount + item1.Amount;
                                    }
                                }
                            }
                            prevweekday = d.Date.Day;
                            <div class="col-sm-2">$@amount</div>
                        }
                    }
                </div>
            }
        }
    </div>
    <div class="col-sm-6">
        <h2>Description</h2>
        <div class="issue-description">
            Here this view shows some tabular static data. Your job is to make data dynamically come from a data source provided found in <strong>Helper/DataProvider/Report</strong> Function. Let's consider a scenario where employees get paid on daily basis. You will have to calculate the weekly payment received by an employee and show it in the tabular format based on the month selected in the dropdown.
            <br />
            <br />
            <strong> Instructions </strong>
            <p>**Week will start from the first day of the selected month.</p>
            <p>**Dropdown selection will automatically trigger an event and refresh the page with the selected month passed as a query string.</p>
            <p>**Year will be the current year.</p>
            <p>**<strong>Data:</strong> Daily salary data is provided in the Salary class (date and amount field) as a list inside the Employee class.</p>
            <br />
            <br />
            <div class="clearfix">
                <a class="btn btn-success pull-left" href="/interview/sql">&lt;&lt; Previous</a>
                <a class="btn btn-success pull-right" href="/interview/problem">Next >></a>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
                                        //Script code will go here
    </script>
}

Faq.Interview/Views/Interview/SaveData.cshtml
@model DinnerViewModel
@{
    ViewBag.Title = "Save data  issue";
    TempData["NAV"] = "DATA";
}

<h2>Save data issue</h2>

<div class="row">
    <div class="col-sm-6">
        @using (Html.BeginForm("SaveData", "Interview", FormMethod.Post, new { autocomplete = "off" }))
        {
            @Html.ValidationSummary(true)

            @Html.AntiForgeryToken()


            <div class="form-group">
                @Html.LabelFor(model => model.Name, "Name", new { @class = "control-label" })
                <div class="control">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", autocomplete = "off", @readonly = "true" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, "Description", new { @class = "control-label" })
                <div class="control">
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", autocomplete = "off", @readonly = "true" })
                </div>
            </div>

            <h4>Sizing Information</h4>
            <div class="row mgt">
                <div class="col-sm-3 mgb"><strong>Sizes</strong></div>
                <div class="col-sm-4  mgb"><strong>Price($)</strong> </div>
                <div class="col-sm-4  mgb"><strong>Unit(kg)</strong></div>

                @for(var i = 0; i < Model.Sizes.Count; i++)
                {
                    <div class="col-sm-3 mgb">
                        @Html.Label(Model.Sizes[i].Name, new { @class = "control-label" })
                        @Html.HiddenFor(model => model.Sizes[i].Name)
                    </div>
                    <div class="col-sm-4 mgb">
                        @Html.TextBoxFor(model => model.Sizes[i].Price, new { @class = "form-control", autocomplete = "off", @readonly = "true" })
                    </div>
                    <div class="col-sm-4 mgb">
                        @Html.TextBoxFor(model => model.Sizes[i].Unit, new { @class = "form-control", autocomplete = "off", @readonly = "true" })
                    </div>
                }
            </div>
            
            <div class="form-group">
                <div class="control action clearfix">
                    <button type="submit" class="btn btn-success">
                        Save
                    </button>
                </div>
            </div>
        }
    </div>
    <div class="col-sm-6">
        <h2>Description</h2>
        <div class="issue-description">
            We have some data in this form, hitting the Save button all data should receive by POST(savedata) function including sizing information array.
            <br />
            <br />
            There are 2 issues <br />
            1) Exception
            <br />
            2) Sizing information does not pass through.
            <br />
            <br />
            <strong>Please solve these issues so that the controller function receives data accordingly.</strong>

            <br />
            <br />
            <div class="clearfix">
                <a class="btn btn-success pull-left" href="/interview/index">&lt;&lt; Previous</a>
                <a class="btn btn-success pull-right" href="/interview/sql">Next >></a>
            </div>
        </div>
    </div>
</div>

Faq.Interview/Views/Interview/Sql.cshtml
@{
    ViewBag.Title = "SQL Issue";
    TempData["NAV"] = "SQL";
}

<h2>Write SQL query</h2>

You are given a script that will generate some data set. Script is inside the SQL Folder in the root directory. Run that script. Please update your query in query.sql file inside SQL folder.

<h3>Requirements</h3>
<p>Find the employees of highest two ranks (highest - 1, lowest - 5) and serialize them based on their salary in descending order. Also, find the salary difference of each employee from the highest paid employee of the same rank. If an employee has the highest salary within the same ranked employees then mark it as “Max Salary”.</p>

<h3>Table Data</h3>
<img src="~/Images/sql_raw_table.png" />

<h3>Output</h3>
<img src="~/Images/sql_output.png" />

<br />
<br />
<div>
    <a class="btn btn-success pull-left" href="/interview/savedata">Previous</a>
    <a class="btn btn-success pull-right" href="/interview/report">Next >></a>
</div>

Faq.Interview/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    @RenderSection("Meta", required: false)
    <link rel="icon" href="/favicon.ico">
    <title>@ViewBag.Title - Interview</title>
    <!-- CSS -->
    <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400" />
    <link type="text/css" rel="stylesheet" href="/Styles/font-awesome.min.css" />
    <link type="text/css" rel="stylesheet" href="/Styles/bootstrap.min.css" />

    @RenderSection("Styles", required: false)
    @Styles.Render("~/Styles/Site")
    <!-- JS -->
    <script type="text/javascript" src="/Scripts/modernizr-2.6.2.js"></script>
    <script type="text/javascript" src="/Scripts/jquery-1.10.2.min.js"></script>
    @RenderSection("Head", required: false)
</head>
<body class="@ViewBag.BodyClass">
  
        <div class="topnav clearfix">
            <div class="container">

                <div class="logo">
                    <a href="/">
                        <img src="/Images/logo.png" alt="" />
                    </a>
                </div>
                <ul>
                    <li class="text">
                       
                    </li>
                </ul>

            </div>
        </div>
    }

    @if (ViewBag.ShowMenu == false)
    {
        <div class="main">
            <div class="container">
                @RenderBody()
            </div>
        </div>
    }
    else
    {
        <div class="main">
            <div class="container">
                <div class="sidenav">
                    <ul>
                        <li>
                            <div style="color: red; line-height: 1.3">Please make sure that you read the instructions in the Instructions link first before you start. <br /> <br /></div>
                        </li>
                        <li>
                            <a href="/Interview/Index?showInstructions=true" class="@(TempData["NAV"] != null && TempData["NAV"].ToString() == "INDEX" ? "selected" : "")">
                                Instructions
                            </a>
                        </li>
                        <li>
                            <a href="/interview/savedata" class="@(TempData["NAV"] != null && TempData["NAV"].ToString() == "DATA" ? "selected" : "")">
                                Data Post Issue
                            </a>
                        </li>
                        <li>
                            <a href="/interview/Sql" class="@(TempData["NAV"] != null && TempData["NAV"].ToString() == "SQL" ? "selected" : "")">
                                SQL
                            </a>
                        </li>

                        <li>
                            <a href="/interview/report" class="@(TempData["NAV"] != null && TempData["NAV"].ToString() == "REPORT" ? "selected" : "")">
                                Report
                            </a>
                        </li>
                        <li>
                            <a href="/interview/problem" class="@(TempData["NAV"] != null && TempData["NAV"].ToString() == "PROBLEM" ? "selected" : "")">
                                Solve This Problem
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="leftpad">
                    @RenderBody()
                </div>
            </div>
        </div>
    }

    <div id="loading"></div>

    <script type="text/javascript" src="/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="/Scripts/globalize.js"></script>
    <script type="text/javascript" src="/Scripts/globalize.culture.en-AU.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>